[project]
name = "Oroboro"
version = "0.1.0"
description = "Event-driven Temporal Expressions in Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.5",
]

[project.urls]
Homepage = "https://github.com/sheffler/Oroboro"
